Adding sns sqs example
epsagon/epsagon-dotnet pull request #14
Opened 2020-08-27 16:24 UTC by enoodle

2020-08-30 07:03 UTC, tvaintrob requested changes

2020-08-30 07:03 UTC, tvaintrob commented on examples/sns-sqs-lambda/aws-csharp.csproj
> +    <PackageReference Include="Microsoft.Win32.Primitives" Version="4.3.0" />
why is that required?

2020-08-31 04:27 UTC, enoodle commented on examples/sns-sqs-lambda/aws-csharp.csproj
> +    <PackageReference Include="Microsoft.Win32.Primitives" Version="4.3.0" />
did work for me without that.

2020-09-01 07:46 UTC, tvaintrob commented on examples/sns-sqs-lambda/Handler.cs
> +        public override Response HandlerFunction(Request request, ILambdaContext context)
marking the function with `async` and changing the return type to `Task<Response>` will solve this issue

2020-09-02 12:13 UTC, tvaintrob approved these changes

2020-09-02 12:16 UTC, merged